services:
  app:
    build: .
    platform: linux/arm64
    container_name: parser
    restart: always
    volumes:
      - .:/app
    depends_on:
      - selenium
      - mongodb
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
      MONGODB_URL: mongodb://admin:admin@mongodb:27017/

  selenium:
#    image: selenium/standalone-chromium:latest # Для AMD64
    image: seleniarm/standalone-chromium:latest # Для ARM64
    container_name: selenium
    restart: unless-stopped
    shm_size: 2g
    ports:
      - 4444:4444  # Selenium WebDriver API
#      - 7900:7900  # VNC Viewer
    environment:
      SE_NODE_MAX_SESSIONS: 1
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_SESSION_TIMEOUT: 90
      SE_NODE_GRID_URL: http://localhost:4444
      SE_NODE_DETECT_DRIVERS: false

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
